### PR TITLE
Added Dashicons for Buttons / Added German translation

### PR DESCRIPTION
**Pull request by tmconnect**
Hi John,

first thanks for this great plugin!

I rather like icons for the toolbar. So I made some changes to use the WP Dashicons for the toolbar and the field settings page. This needs a little changing for the `acf/medium-editor-field/custom-buttons`, so I changed this part on the README as well.

Also I added a .pot file for translation and the German translation, too.

Hope you like this...
Thomas

### CODE REVIEW

**Comment by Hube2** [comment]
Just wanted to let you know that I'm not ignoring this. There is quite a bit in it and I just need the time to review everything. I'll look at it as soon as I can give it the attention it deserves to review and test it.

~JH

**Comment by Hube2** [comment]
Thank you,

I have updated the version and pushed the changes to the wordpress.org as well

**Comment by tmconnect** [comment]
Glad, that you like my version!

**Comment by Hube2** [comment]
I corrected one bug that had to do with custom buttons. I also added the "anchor" button that you overlooked. Not sure if your interested but thought I'd see if you were interested in updating the translation for me that you were kind enough to add.

**Pull request merged**
